OnlineShoppingStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OnlineShoppingStore.Domain.Entities;

namespace OnlineShoppingStore.WebUI.Models
{
	public class CartIndexViewModel
	{
		public Cart Cart { get; set; }
		public string ReturnUrl { get; set; }
	}
}

OnlineShoppingStore.WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.WebUI.Models
{
	public class LoginViewModel
	{
		[Required(ErrorMessage ="Username is required")]
		public string UserName { get; set; }

		[Required(ErrorMessage = "Password is required")]
		[StringLength(50, MinimumLength =6)]
		public string Password { get; set; }
	}
}

OnlineShoppingStore.WebUI/Models/PageInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OnlineShoppingStore.WebUI.Models
{
	public class PageInfo
	{
		public int TotalItems { get; set; }
		public int ItemsPerPage { get; set; }
		public int CurrentPage { get; set; }
		public int TotalPages
		{
			get
			{
				return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
			}
		}
	}
}

OnlineShoppingStore.WebUI/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using OnlineShoppingStore.Domain.Entities;

namespace OnlineShoppingStore.WebUI.Models
{
	public class ProductListViewModel
	{
		public IEnumerable<Product> Products { get; set; }
		public PageInfo PageInfo { get; set; }
		public string CurrentCategory { get;  set; }
	}
}

OnlineShoppingStore.WebUI/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using OnlineShoppingStore.Domain.Interfaces;
using OnlineShoppingStore.WebUI.Models;

namespace OnlineShoppingStore.WebUI.Controllers
{
	[Authorize]
	public class AccountController : Controller
	{
		IAuthentication authentication;

		public AccountController(IAuthentication authentication)
		{
			this.authentication = authentication;
		}

		[AllowAnonymous]
		public ActionResult Login()
		{
			return View();
		}

		[HttpPost]
		[AllowAnonymous]
		public ActionResult Login(LoginViewModel model, string returnUrl)
		{
			if (ModelState.IsValid)
			{
				if (authentication.Authenticate(model.UserName, model.Password))
				{
					FormsAuthentication.SetAuthCookie(model.UserName, false);
					return Redirect(returnUrl ?? Url.Action("Index", "Admin"));
				}
				else
				{
					ModelState.AddModelError("", "Incorrect username or password");
					return View();
				}
			}
			else
			{
				return View();
			}
		}

		public ActionResult Logout()
		{
			FormsAuthentication.SignOut();
			return RedirectToAction("Index", "Admin");
		}

		//Change Password
		//Forget Password
	}
}

OnlineShoppingStore.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.Domain.Interfaces;

namespace OnlineShoppingStore.WebUI.Controllers
{
	[Authorize]
	public class AdminController : Controller
	{
		IProductRepository repository;

		public AdminController(IProductRepository repo)
		{
			repository = repo;
		}
		public ActionResult Index()
		{
			return View(repository.Products);
		}

		public ViewResult Create()
		{
			return View(new Product());
		}

		[HttpPost]
		public ActionResult Create(Product product)
		{
				if (ModelState.IsValid)
				{
					repository.SaveProduct(product);
					TempData["message"] = string.Format("{0} has been saved", product.Name);

					return RedirectToAction("Index");
				}
				else
				{
					return View(product);
				}
		}

		public ViewResult Edit(int productId)
		{
			Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

			return View(product);
		}

		[HttpPost]
		public ActionResult Edit(Product product)
		{
			if (ModelState.IsValid)
			{
				repository.SaveProduct(product);
				TempData["message"] = string.Format("{0} has been saved", product.Name);

				return RedirectToAction("Index");
			}
			else
			{
				return View(product);
			}
		}

		[HttpPost]
		public ActionResult Delete(int productId)
		{
			Product deleteProduct = repository.DeleteProduct(productId);
			if (deleteProduct != null)
			{
				TempData["message"] = string.Format("{0} was deleted", deleteProduct.Name);
			}

			return RedirectToAction("Index");
		}
	}
}

OnlineShoppingStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.Domain.Interfaces;
using OnlineShoppingStore.WebUI.Models;

namespace OnlineShoppingStore.WebUI.Controllers
{
	public class CartController : Controller
	{
		private IProductRepository repository;
		private IOrderProcessor orderProcessor;

		public CartController(IProductRepository repo, IOrderProcessor proc)
		{
			repository = repo;
			orderProcessor = proc;
		}

		public ViewResult Index(Cart cart, string returnUrl)
		{
			return View(new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl });
		}

		public PartialViewResult Summary(Cart cart)
		{
			return PartialView(cart);
		}

		
		public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
		{
			Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

			if(product != null)
			{
				cart.AddItem(product, 1);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

		public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
		{
			Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);

			if(product != null)
			{
				cart.RemoveLine(product);
			}

			return RedirectToAction("Index", new { returnUrl });
		}

		[HttpGet]
		public ViewResult Checkout()
		{
			return View(new ShippingDetails());
		}

		[HttpPost]
		public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
		{
			if (cart.Lines.Count() == 0)
			{
				ModelState.AddModelError("", "Sorry your cart is empty!");
			}
			if (ModelState.IsValid)
			{
				orderProcessor.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed");
			}
			else
			{
				return View(shippingDetails);
			}
		}

	}
}

OnlineShoppingStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Interfaces;

namespace OnlineShoppingStore.WebUI.Controllers
{
	public class NavController : Controller
	{
	   private IProductRepository repository;

		public NavController(IProductRepository repo)
		{
			repository = repo;
		}

	   public PartialViewResult Menu()
		{
			IEnumerable<string> categories = repository.Products
											 .Select(x => x.Category)
											 .Distinct()
											 .OrderBy(x => x);
			return PartialView(categories);
		}
	}
}

OnlineShoppingStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Interfaces;
using OnlineShoppingStore.WebUI.Models;

namespace OnlineShoppingStore.WebUI.Controllers
{
	public class ProductController : Controller
	{
		private readonly IProductRepository repository;
		public int PageSize = 4;

		public ProductController(IProductRepository repo)
		{
			repository = repo;
		}
		// GET: Product
		public ViewResult List(string category, int page = 1)
		{
			ProductListViewModel model = new ProductListViewModel
			{
				Products = repository.Products
				        .Where(p=> category == null || p.Category == category)
						.OrderBy(p => p.ProductId)
						.Skip((page - 1) * PageSize)
						.Take(PageSize),
				PageInfo = new PageInfo
				{
					CurrentPage = page,
					ItemsPerPage = PageSize,
					TotalItems = category == null ?
					           repository.Products.Count() :
							   repository.Products.Where(p=>p.Category == category).Count()
		        },
				CurrentCategory = category
	        };
			return View(model);
		  }
	 }
}

OnlineShoppingStore.WebUI/Views/Admin/Create.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineShoppingStore.WebUI/Views/Admin/Edit.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OnlineShoppingStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<OnlineShoppingStore.Domain.Entities.Product>

@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
	<div class="panel-heading">
		<div>All Products</div>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed table-bordered">
			<tr>
				<th class="text-right">ID</th>
				<th>Name</th>
				<th class="text-right">Price</th>
				<th class="text-center">Actions</th>
			</tr>
			@foreach (var item in Model)
			{
				<tr>
					<td class="text-right">@item.ProductId</td>
					<td>@Html.ActionLink(item.Name, "Edit", new { item.ProductId})</td>
					<td class="text-right">@item.Price.ToString("c")</td>
					<td class="text-center">
						@using (Html.BeginForm("Delete", "Admin"))
						{
							@Html.Hidden("ProductId", item.ProductId)
							<input type="submit" class="btn btn-default btn-xs" value="Delete"/>
						}
					</td>
				</tr>
			}
		</table>
	</div>
	<div class="panel-footer">
		@Html.ActionLink("Add a New Product", "Create", null, new { @class="btn btn-default"})
	</div>
</div>

OnlineShoppingStore.WebUI/Views/Cart/Checkout.cshtml
@model OnlineShoppingStore.Domain.Entities.ShippingDetails

@{
	ViewBag.Title = "Online Shopping Store: Checkout";
}

<h2>Check out now</h2>
<p>Please enter your details and we will ship your goods right away!</p>

 @using (Html.BeginForm())
 {
	 @Html.ValidationSummary()
	 <h3>Ship to</h3>
	 <div class="form-group">
		 <label>Name:</label>
		 @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
	 </div>
	<h3>Address</h3>
	<div class="form-group">
		<label>Line 1:</label>
		@Html.TextBoxFor(x => x.Line1, new { @class = "form-control" })
	</div>
	<div class="form-group">
		<label>Line 2:</label>
		@Html.TextBoxFor(x => x.Line2, new { @class = "form-control" })
	</div>
	<div class="form-group">
		<label>Line 3:</label>
		@Html.TextBoxFor(x => x.Line3, new { @class = "form-control" })
	</div>
	<div class="form-group">
		<label>City:</label>
		@Html.TextBoxFor(x => x.City, new { @class = "form-control" })
	</div>
	<div class="form-group">
		<label>State:</label>
		@Html.TextBoxFor(x => x.State, new { @class = "form-control" })
	</div>
	<div class="form-group">
		<label>Zip:</label>
		@Html.TextBoxFor(x => x.Zip, new { @class = "form-control" })
	</div>
	<div class="form-group">
		<label>Country:</label>
		@Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
	</div>
	<h3>Options</h3>
	<div class="checkbox">
		<label>@Html.EditorFor(x => x.GiftWrap)
		  Gift wrap these items
		</label>
	</div>
	<div class="text-center">
		<input class="btn btn-primary" type="submit" value="Complete order" />
	</div>
 }

OnlineShoppingStore.WebUI/Views/Cart/Completed.cshtml
@{
	ViewBag.Title = "Online Shopping Store:  Order Submitted";
}
<h2>Thanks!</h2>
Thanks for placing your order. We'll ship your goods as soon as possible.

OnlineShoppingStore.WebUI/Views/Cart/Index.cshtml
@model OnlineShoppingStore.WebUI.Models.CartIndexViewModel

<style>
	#cartTable td {
	  vertical-align: middle;
	}
</style>

@{
	ViewBag.Title = "Sports Store: Your Cart";
}

<h2>Your cart</h2>
<table id="cartTable" class="table">
	<thead>
		<tr>
			<th>Quantity</th>
			<th>Item</th>
			<th class="text-right">Price</th>
			<th class="text-right">Subtotal</th>
		</tr>
	</thead>
	<tbody>
		@foreach(var line in Model.Cart.Lines)
		{
			<tr>
				<th class="text-center">@line.Quantity</th>
				<th class="text-left">@line.Product.Name</th>
				<th class="text-right">@line.Product.Price.ToString("c")</th>
				<td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
				<td>
					@using (Html.BeginForm("RemoveFromCart", "Cart")) {
						@Html.Hidden("ProductId", line.Product.ProductId)
						@Html.HiddenFor(x=>x.ReturnUrl)
						<input class="btn btn-sm btn-warning" type="submit" value="Remove" />
					}
				</td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<td colspan="3" class="text-right">Total:</td>
			<td class="text-right">
				@Model.Cart.ComputeTotalValue().ToString("c")
			</td>
		</tr>
	</tfoot>
</table>
<div class="text-center">
	<a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
	@Html.ActionLink("Checkout now", "Checkout", null, 
	new { @class = "btn btn-primary"})
</div>

OnlineShoppingStore.WebUI/Views/Cart/Summary.cshtml
@model OnlineShoppingStore.Domain.Entities.Cart

<div class="navbar-right">
	@Html.ActionLink("Checkout", "Index", "Cart",
	new { returnUrl = Request.Url.PathAndQuery},
	new { @class = "btn btn-default navbar-btn"})
</div>
<div class="navbar-text navbar-right">
	<b>Your cart:</b>
	@Model.Lines.Sum(x=>x.Quantity) item(s),
	@Model.ComputeTotalValue().ToString("c")
</div>

OnlineShoppingStore.WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product", null, 
	new { @class = "btn btn-block btn-default btn-lg"})


@foreach (var link in Model)
{
	@Html.RouteLink(link, new
{
	controller = "Product",
	action = "List",
	category = link,
	page = 1
},

	new
	{
		@class = "btn btn-block btn-default btn-lg"
		+ (link == ViewBag.SelectedCategory? " btn-primary" : "")
	}

)
}

OnlineShoppingStore.WebUI/Views/Product/List.cshtml
@model OnlineShoppingStore.WebUI.Models.ProductListViewModel

@{
	ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
	@Html.Partial("ProductSummary", p)
}

<div class="btn-group pull-right">
	@Html.PageLinks(Model.PageInfo, x=> Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

OnlineShoppingStore.WebUI/Views/Shared/ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entities.Product

<div class="well">
	<h4>
		<strong>@Model.Name</strong>
		<span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
	</h4>
	@using (Html.BeginForm("AddToCart", "Cart")) {
		<div class="pull-right">
			@Html.HiddenFor(x=>x.ProductId)
			@Html.Hidden("returnUrl", Request.Url.PathAndQuery)
			<input type="submit" class="btn btn-success" value="Add To Cart" />
		</div>
	}
	<span class="lead">@Model.Description</span>
</div>

OnlineShoppingStore.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
	<link href="~/Content/bootstrap.css" rel="stylesheet" />
	<title></title>
</head>
<body>
	<div>
		@if (TempData["message"] != null)
		{
			<div class="alert alert-success">@TempData["message"]</div>
		}
		@{
			var userName = HttpContext.Current.User.Identity.Name;
			if (userName != "")
			{
				<h3>@Html.ActionLink("Online Shopping Store", "List", "Product")
		            <span class="btn-info btn pull-right">
						@Html.ActionLink(HttpContext.Current.User.Identity.Name + " - Logout", "Logout", "Account")
					</span>
		        </h3>
			}
		}
		@RenderBody()
	</div>
</body>
</html>

OnlineShoppingStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title - Online Shopping Store</title>
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
	<link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
	<div class="navbar navbar-inverse" role="navigation">
		<a class="navbar-brand" href="#">
			<span class="hidden-xs">Online Shopping Store</span>
			<span class="visible-xs">Online</span>
			<span class="visible-xs">Shopping</span>
			<span class="visible-xs">Store</span>
		</a>
		@Html.Action("Summary", "Cart")
	</div> 
	<div class="row panel">
		<div id="categories" class="col-lg-3">
			@Html.Action("Menu", "Nav")
		</div>
		<div class="col-lg-7">
		   @RenderBody()
		</div>
	</div>
</body>
</html>